scr/Web/Controllers/EmployeeController.cs
using AutoMapper;
using Core.DTOs;
using Core.Entities;
using Core.Exceptions;
using Core.Interfaces.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web.Models.Employee;

namespace Web.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployeeService _employeeService;
        private readonly IPositionService _positionService;
        private readonly IDepartmentService _departmentService;
        private readonly IEquipmentService _equipmentService;

        public EmployeeController(IEmployeeService employeeService,
            IPositionService positionService,
            IDepartmentService departmentService,
            IEquipmentService equipmentService)
        {
            _employeeService = employeeService;
            _positionService = positionService;
            _departmentService = departmentService;
            _equipmentService = equipmentService;
        }

        [HttpGet]
        public IActionResult Index(string searchSelectionString, string searchString, string searchPosition, string searchDepartment,
            bool move, int? equipmentId)
        {
            if (move && equipmentId != null)
            {
                ViewBag.Move = true;
                ViewBag.EquipmentId = equipmentId.Value;
            }
            else
            {
                ViewBag.Move = false;
            }    


            var employees = _employeeService.GetAll();
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<EmployeeDTO, EmployeeViewModel>()).CreateMapper();
            var employeesViewModels = mapper.Map<IEnumerable<EmployeeDTO>, List<EmployeeViewModel>>(employees);

            // departments
            List<string> departments = _departmentService.GetAllName().ToList();
            departments.Insert(0, "Отдел");

            if (searchDepartment != string.Empty && searchDepartment != "Отдел" && searchDepartment != null)
            {
                employeesViewModels = employeesViewModels.Where(p => p.DepartmentName == searchDepartment).ToList();
            }

            // position
            List<string> positions = _positionService.GetAllName().ToList();
            positions.Insert(0, "Должность");

            if (searchPosition != string.Empty && searchPosition != "Должность" && searchPosition != null)
            {
                employeesViewModels = employeesViewModels.Where(p => p.PositionName == searchPosition).ToList();
            }

            // list search
            List<string> searchSelection = new List<string>() { "Поиск", "Коду", "ФИО", "Телефону" };

            // search
            if (searchSelectionString != string.Empty && searchSelectionString != null && searchSelectionString != "Поиск" && searchString != null)
            {
                if (searchSelection[1].ToLower() == searchSelectionString.ToLower() && searchString != string.Empty)
                {
                    employeesViewModels = employeesViewModels.Where(p => p.Id.ToString() != null && p.Id.ToString().ToLower().Equals(searchString.ToLower())).ToList();
                }
                else if (searchSelection[1].ToLower() == searchSelectionString.ToLower() && searchString == string.Empty)
                {
                    employeesViewModels = employeesViewModels.Where(p => p.Id.ToString() == null || p.Id.ToString() == string.Empty).ToList();
                }
                else if (searchSelection[2].ToLower() == searchSelectionString.ToLower() && searchString != string.Empty)
                {
                    employeesViewModels = employeesViewModels.Where(p => p.FullName != null && p.FullName.ToLower().Contains(searchString.ToLower())).ToList();
                }
                else if (searchSelection[2].ToLower() == searchSelectionString.ToLower() && searchString == string.Empty)
                {
                    employeesViewModels = employeesViewModels.Where(p => p.FullName == null || p.FullName == string.Empty).ToList();
                }
                else if (searchSelectionString.ToLower() == searchSelection[3].ToLower() && searchString != string.Empty)
                {
                    employeesViewModels = employeesViewModels.Where(p => p.Phone.ToString().Contains(searchString)).ToList();
                }
                else if (searchSelectionString.ToLower() == searchSelection[3].ToLower() && searchString == string.Empty)
                {
                    employeesViewModels = employeesViewModels.Where(p => p.Phone == null || p.Phone == string.Empty).ToList();
                }

            }

            return View(new EmployeeIndexViewModel()
            {
                EmployeeViewModels = employeesViewModels,
                SearchSelection = new SelectList(searchSelection),
                SearchSelectionString = searchSelectionString,
                SearchString = searchString,
                DepartmentSelect = new SelectList(departments),
                SearchDepartment = searchDepartment,
                PositionSelect = new SelectList(positions),
                SearchPosition = searchPosition,
                Move = move,
                EquipmentId = equipmentId
            });
        }


        [HttpPost]
        public IActionResult Move(int id, string searchSelectionString, string searchString, string searchPosition, string searchDepartment, int equipmentId)
        {
            var equipment = _equipmentService.Get(equipmentId);
            var newEmp = _employeeService.Get(id);
            var newEmpInfoName = newEmp.Id + "|" + newEmp.FullName;
            string oldEmployeeFullName = equipment.Id +"|" +equipment.EmployeeFullName;

            try
            {
                equipment.EmployeeFullName = newEmpInfoName;
                _equipmentService.Edit(equipment);
            }
            catch (ValidationException)
            {
                return RedirectToAction("Error", "Home", new { requestId = "400", errorInfo = string.Empty });
            }

            string oldDepartment = equipment.Department;
            string newDepartment = newEmp.DepartmentName;
            string newEmployeeFullName = newEmpInfoName;

            return RedirectToAction("MoveSuccess", new
            {
                equipment.Name,
                equipment.InventoryNumber,
                oldDepartment,
                oldEmployeeFullName,
                newDepartment,
                newEmployeeFullName
            });
        }

        [HttpGet]
        public IActionResult MoveSuccess(MoveSuccessViewModel model)
        {
            ViewBag.Name = model.Name;
            ViewBag.InventoryNumber = model.InventoryNumber;
            ViewBag.OldDepartment = model.OldDepartment;
            ViewBag.OldEmployeeFullName = model.OldEmployeeFullName;
            ViewBag.NewDepartment = model.NewDepartment;
            ViewBag.NewEmployeeFullName = model.NewEmployeeFullName;

            return View();
        }

        [HttpGet]
        public IActionResult Add(string searchSelectionString, string searchString, string searchPosition, string searchDepartment)
        {
            ViewBag.SearchSelectionString = searchSelectionString;
            ViewBag.SearchString = searchString;
            ViewBag.SearchDepartment = searchDepartment;
            ViewBag.SearchPosition = searchPosition;
           
            // departments
            List<string> departments = _departmentService.GetAllName().ToList();

            // positions
            List<string> positions = _positionService.GetAllName().ToList();

            return View(new EmployeeAddEditViewModel()
            {
                EmployeeViewModel = new EmployeeViewModel() {  },
                DepartmentSelect = new SelectList(departments),
                PositionSelect = new SelectList(positions)
            });
        }

        [HttpPost]
        public IActionResult Add(EmployeeAddEditViewModel model, string searchSelectionString, string searchString, string searchPosition, string searchDepartment)
        {
            ViewBag.SearchSelectionString = searchSelectionString;
            ViewBag.SearchString = searchString;
            ViewBag.SearchDepartment = searchDepartment;
            ViewBag.SearchPosition = searchPosition;

            if (ModelState.IsValid)
            {
                var employeeDTO = new EmployeeDTO()
                {
                    Id = model.EmployeeViewModel.Id,
                    DateOfBirth = model.EmployeeViewModel.DateOfBirth,
                    FullName = model.EmployeeViewModel.FullName,
                    DepartmentName = model.EmployeeViewModel.DepartmentName,
                    Phone = model.EmployeeViewModel.Phone,
                    PositionName = model.EmployeeViewModel.PositionName,
                    Sex = model.EmployeeViewModel.Sex
                };

                try
                {
                    _employeeService.Add(employeeDTO);

                    return RedirectToAction("Index", new
                    {
                        searchSelectionString,
                        searchString,
                        searchPosition,
                        searchDepartment
                    });
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError(ex.Property, ex.Message);
                }
            }

            // departments
            List<string> departments = _departmentService.GetAllName().ToList();

            // positions
            List<string> positions = _positionService.GetAllName().ToList();

            model.DepartmentSelect = new SelectList(departments);
            model.PositionSelect = new SelectList(positions);
          
            return View(model);
        }

scr/Web/Controllers/ReportController.cs
using Core.Exceptions;
using Core.Interfaces.Services;
using Core.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web.Models.Report;
using Web.Reports;

namespace Web.Controllers
{
    [Authorize(Roles = "admin")]
    public class ReportController : Controller
    {
        private readonly IReportService _reportService;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IStatusEquipmentService _statusEquipmentService;
        private readonly IDepartmentService _departmentService;

        public ReportController(IReportService reportService,
               IWebHostEnvironment webHostEnvironment,
               IStatusEquipmentService statusEquipmentService,
               IDepartmentService departmentService)
        {
            _reportService = reportService;
            _webHostEnvironment = webHostEnvironment;
            _statusEquipmentService = statusEquipmentService;
            _departmentService = departmentService;
        }

        public IActionResult Index(string exMessage)
        {
            if (exMessage != null)
            {
                ViewBag.ExMessage = exMessage;
            }
            else
            {
                ViewBag.ExMessage = null;
            }

            // statusEquipments
            List<string> statusEquipments = _statusEquipmentService.GetAllName().ToList();
            statusEquipments.Insert(0, "Состояние оборудования");

            // departments
            List<string> departments = _departmentService.GetAllName().ToList();
            departments.Insert(0, "Отдел");

            //if (searchDepartment != string.Empty && searchDepartment != "Отдел" && searchDepartment != null)
            //{
            //    employeesViewModels = employeesViewModels.Where(p => p.DepartmentName == searchDepartment).ToList();
            //}

            return View(new ReportIndexViewModel()
            { 
                StatusSelect = new SelectList(statusEquipments),
                DepartmentSelect = new SelectList(departments)
            });
        }


        [HttpPost]
        public IActionResult GetReportEquipments(string searchStatusEquipment)
        {
            string exMessage = null;

            try
            {

                if (searchStatusEquipment == "Состояние оборудования")
                {
                    List<List<string>> reportEquipments = _reportService.GetReportEquipments();
                    string title = "Отчёт оборудования";

                    ReportPDF report = new ReportPDF(_webHostEnvironment);
                    return File(report.Report(reportEquipments, title), "application/pdf");
                }
                else
                {
                    List<List<string>> reportEquipments = _reportService.GetReportEquipmentsByStatus(searchStatusEquipment);
                    string title = $"Отчёт оборудования по состоянию оборудования: {searchStatusEquipment}";

                    ReportPDF report = new ReportPDF(_webHostEnvironment);
                    return File(report.Report(reportEquipments, title), "application/pdf");
                }
            }
            catch (ValidationException ex)
            {
                exMessage = ex.Message;
            }
            return RedirectToAction("Index", new
            {
                exMessage
            });
        }

        [HttpPost]
        public IActionResult GetReportDepartments(string searchDepartment)
        {
            string exMessage = null;

            try
            {

                if (searchDepartment == "Отдел")
                {
                    List<List<string>> reportEmployees = _reportService.GetReportEmployee();
                    string title = "Отчёт сотрудников";

                    ReportPDF report = new ReportPDF(_webHostEnvironment);
                    return File(report.Report(reportEmployees, title), "application/pdf");
                }
                else
                {
                    List<List<string>> reportEquipments = _reportService.GetReportEmployeeByDepartment(searchDepartment);
                    string title = $"Отчёт сорудников по отделу: {searchDepartment}";

                    ReportPDF report = new ReportPDF(_webHostEnvironment);
                    return File(report.Report(reportEquipments, title), "application/pdf");
                }
            }
            catch (ValidationException ex)
            {
                exMessage = ex.Message;
            }
            return RedirectToAction("Index", new
            {
                exMessage
            });
        }

        [HttpPost]
        public IActionResult GetReportEquipmentsByEmployees(string searchEmployee)
        {
            string exMessage = null;

            try
            {
                    List<List<string>> reportEmployees = _reportService.GetReportEquipmentsByEmployees();
                    string title = "Отчёт оборудования по работникам";

                    ReportPDF report = new ReportPDF(_webHostEnvironment);
                    return File(report.Report(reportEmployees, title), "application/pdf");
            }
            catch (ValidationException ex)
            {
                exMessage = ex.Message;
            }
            return RedirectToAction("Index", new
            {
                exMessage
            });
        }
    }
}

scr/Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <link type="text/css" rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                <img style="width: 50px; height: 50px;" title="Учет оборудования" alt="Учет оборудования" src="~/files/Text-Documents-icon.png">
            </a>
            <a class="navbar-brand" href="/">Учет оборудования</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            @if (Context.Request.Path.ToString().ToLower().Contains("equipment") && !Context.Request.Path.ToString().ToLower().Contains("statusequipment") 
                                && !Context.Request.Path.ToString().ToLower().Contains("equipmenttype"))
                            {
                                <a class="nav-link active" asp-controller="Equipment" asp-action="Index">Оборудование</a>
                            }
                            else
                            {
                                <a class="nav-link" asp-controller="Equipment" asp-action="Index">Оборудование</a>
                            }
                        </li>

                        <li class="nav-item">
                            @if (Context.Request.Path.ToString().ToLower().Contains("statusequipment"))
                            {
                                <a class="nav-link active" asp-controller="StatusEquipment" asp-action="Index">Состояние оборудования</a>
                            }
                            else
                            {
                                <a class="nav-link" asp-controller="StatusEquipment" asp-action="Index">Состояние оборудования</a>
                            }
                        </li>

                        <li class="nav-item">
                            @if (Context.Request.Path.ToString().ToLower().Contains("equipmenttype"))
                            {
                                <a class="nav-link active" asp-controller="EquipmentType" asp-action="Index">Виды оборудования</a>
                            }
                            else
                            {
                                <a class="nav-link" asp-controller="EquipmentType" asp-action="Index">Виды оборудования</a>
                            }
                        </li>

                        <li class="nav-item">
                            @if (Context.Request.Path.ToString().ToLower().Contains("department"))
                            {
                                <a class="nav-link active" asp-controller="Department" asp-action="Index">Отделы</a>
                            }
                            else
                            {
                                <a class="nav-link" asp-controller="Department" asp-action="Index">Отделы</a>
                            }
                        </li>

                        <li class="nav-item">
                            @if (Context.Request.Path.ToString().ToLower().Contains("position"))
                            {
                                <a class="nav-link active" asp-controller="Position" asp-action="Index">Должности</a>
                            }
                            else
                            {
                                <a class="nav-link" asp-controller="Position" asp-action="Index">Должности</a>
                            }
                        </li>
                        <li class="nav-item">
                            @if (Context.Request.Path.ToString().ToLower().Contains("employee"))
                            {
                                <a class="nav-link active" asp-controller="Employee" asp-action="Index">Работники</a>
                            }
                            else
                            {
                                <a class="nav-link" asp-controller="Employee" asp-action="Index">Работники</a>
                            }
                        </li>


                        @if (User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                @if (Context.Request.Path.ToString().ToLower().Contains("users"))
                                {
                                    <a class="nav-link active" asp-controller="Users" asp-action="Index">Пользователи</a>
                                }
                                else
                                {
                                    <a class="nav-link" asp-controller="Users" asp-action="Index">Пользователи</a>
                                }
                            </li>

                            <li class="nav-item">
                                @if (Context.Request.Path.ToString().ToLower().Contains("report"))
                                {
                                    <a class="nav-link active" asp-controller="Report" asp-action="Index">Отчеты</a>
                                }
                                else
                                {
                                    <a class="nav-link" asp-controller="Report" asp-action="Index">Отчеты</a>
                                }
                            </li>
                        }

                        <li class="nav-item">
                            @if (Context.Request.Path.ToString().ToLower().Contains("about"))
                            {
                                <a class="nav-link active" asp-controller="Home" asp-action="About">О нас</a>
                            }
                            else
                            {
                                <a class="nav-link" asp-controller="Home" asp-action="About">О нас</a>
                            }
                        </li>
                    }
                </ul>
                <nav>
                    <ul class="navbar-nav mr-auto">

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item ">
                                <form method="post" asp-controller="Account" asp-action="Logout">
                                    <input class="btnLogout nav-link bg-dark " type="submit" value="Выход" />
                                </form>
                            </li>
                            <li class="nav-item">
                                @if (Context.Request.Path.ToString().ToLower().Contains("profil"))
                                {
                                    <a class="nav-link active right" asp-controller="Account" asp-action="Profile">Профиль</a>
                                }
                                else
                                {
                                    <a class="nav-link right" asp-controller="Account" asp-action="Profile">Профиль</a>
                                }
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                @if (Context.Request.Path.ToString().ToLower().Contains("login"))
                                {
                                    <a class="nav-link active right" asp-controller="Account" asp-action="Login">Вход</a>
                                }
                                else
                                {
                                    <a class="nav-link right" asp-controller="Account" asp-action="Login">Вход</a>
                                }
                            </li>
                        }
                    </ul>
                </nav>
            </div>
        </nav>

    </header>
    <div style="margin-top: 7%;" class="container mtByHeader">
        <main>
            @RenderBody()
        </main>
        <br />
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <a class="linkPrivacy" asp-controller="Home" asp-action="Privacy"> &copy; 2021 - Учет оборудования - Политика конфедициальности</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>