scr/Web/Models/EquipmentType/EquipmentTypeIndexViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace Web.Models.EquipmentType
{
    public class EquipmentTypeIndexViewModel
    {
        public List<EquipmentTypeViewModel> EquipmentTypeViewModel { get; set; }
        public SelectList SearchSelection { get; set; }
        public string SearchString { get; set; }
        public string SearchSelectionString { get; set; }
    }
}

scr/Web/Models/EquipmentType/EquipmentTypeViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Web.Models.EquipmentType
{
    public class EquipmentTypeViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Укажите вид оборудования")]
        [Display(Name = "Вид оборудования")]
        public string Name { get; set; }
    }
}

scr/Web/Controllers/EquipmentController.cs
using AutoMapper;
using ClosedXML.Excel;
using Core.DTOs;
using Core.Entities;
using Core.Exceptions;
using Core.Interfaces.Services;
using Core.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Web.Models.Employee;
using Web.Models.Equipment;

namespace Web.Controllers
{
    public class EquipmentController : Controller
    {
        public readonly IEquipmentService _equipmentService;
        public readonly IStatusEquipmentService _statusEquipmentService;
        public readonly IEmployeeService _employeeService;
        public readonly IEquipmentTypeService _equipmentTypeService;

        public EquipmentController(IEquipmentService equipmentService,
            IStatusEquipmentService statusEquipmentService,
            IEmployeeService employeeService,
            IEquipmentTypeService equipmentTypeService)
        {
            _equipmentService = equipmentService;
            _statusEquipmentService = statusEquipmentService;
            _employeeService = employeeService;
            _equipmentTypeService = equipmentTypeService;
        }

        [HttpGet]
        public IActionResult Index(string searchSelectionString, string searchString,
            string searchStatusEquipment,
            string searchEmployee,
            string searchEquipmentType)
        {
           var equipmentIndexViewModel = GetEquipmentIndexViewModel(searchSelectionString,  searchString, searchStatusEquipment,
             searchEmployee,
             searchEquipmentType);

            return View(equipmentIndexViewModel);
        }

        private EquipmentIndexViewModel GetEquipmentIndexViewModel(string searchSelectionString, string searchString,
            string searchStatusEquipment,
            string searchEmployee,
            string searchEquipmentType)
        {
            var equipmentDTOs = _equipmentService.GetAll();
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<EquipmentDTO, EquipmentViewModel>()).CreateMapper();
            var equipmentViewModels = mapper.Map<IEnumerable<EquipmentDTO>, List<EquipmentViewModel>>(equipmentDTOs);

            // equipmentTypes
            List<string> equipmentTypes = _equipmentTypeService.GetAllName().ToList();
            equipmentTypes.Insert(0, "Вид оборудования");

            if (searchEquipmentType != string.Empty && searchEquipmentType != "Вид оборудования" && searchEquipmentType != null)
            {
                equipmentViewModels = equipmentViewModels.Where(p => p.EquipmentTypeName == searchEquipmentType).ToList();
            }

            // statusEquipments
            List<string> statusEquipments = _statusEquipmentService.GetAllName().ToList();
            statusEquipments.Insert(0, "Состояние оборудования");

            if (searchStatusEquipment != string.Empty && searchStatusEquipment != "Состояние оборудования" && searchStatusEquipment != null)
            {
                equipmentViewModels = equipmentViewModels.Where(p => p.StatusEquipmentName == searchStatusEquipment).ToList();
            }

            // employees
            List<string> employees = _employeeService.GetAllIdName().ToList();
            employees.Insert(0, "Работник");

            if (searchEmployee != string.Empty && searchEmployee != "Работник" && searchEmployee != null)
            {
                string[] empSearchArray = searchEmployee.Split('|');
                equipmentViewModels = equipmentViewModels.Where(p => p.EmployeeFullName == empSearchArray[1]).ToList();
            }

            // list search
            List<string> searchSelection = new List<string>() { "Поиск", "Коду", "Инвентарному номеру", "Названию", "Цене", "Сроку полезного использования", "Годовой ставке", "Сумме отчислений в месяц" };

            // search
            if (searchSelectionString != string.Empty && searchSelectionString != null && searchSelectionString != "Поиск" && searchString != null)
            {
                if (searchSelection[1].ToLower() == searchSelectionString.ToLower() && searchString != string.Empty)
                {
                    equipmentViewModels = equipmentViewModels.Where(p => p.Id.ToString() != null && p.Id.ToString().ToLower().Equals(searchString.ToLower())).ToList();
                }
                else if (searchSelection[1].ToLower() == searchSelectionString.ToLower() && searchString == string.Empty)
                {
                    equipmentViewModels = equipmentViewModels.Where(p => p.Id.ToString() == null || p.Id.ToString() == string.Empty).ToList();
                }
                else if (searchSelection[2].ToLower() == searchSelectionString.ToLower() && searchString != string.Empty)
                {
                    equipmentViewModels = equipmentViewModels.Where(p => p.InventoryNumber != null && p.InventoryNumber.ToLower().Contains(searchString.ToLower())).ToList();
                }
                else if (searchSelection[2].ToLower() == searchSelectionString.ToLower() && searchString == string.Empty)
                {
                    equipmentViewModels = equipmentViewModels.Where(p => p.InventoryNumber == null || p.InventoryNumber == string.Empty).ToList();
                }
                else if (searchSelection[3].ToLower() == searchSelectionString.ToLower() && searchString != string.Empty)
                {
                    equipmentViewModels = equipmentViewModels.Where(p => p.Name != null && p.Name.ToLower().Contains(searchString.ToLower())).ToList();
                }
                else if (searchSelection[3].ToLower() == searchSelectionString.ToLower() && searchString == string.Empty)
                {
                    equipmentViewModels = equipmentViewModels.Where(p => p.Name == null || p.Name == string.Empty).ToList();
                }
                else if (searchSelectionString.ToLower() == searchSelection[4].ToLower() && searchString != string.Empty)
                {
                    equipmentViewModels = equipmentViewModels.Where(p => p.Price.ToString().Contains(searchString)).ToList();
                }
                else if (searchSelectionString.ToLower() == searchSelection[4].ToLower() && searchString == string.Empty)
                {
                    equipmentViewModels = equipmentViewModels.Where(p => p.Price == 0).ToList();
                }
                else if (searchSelectionString.ToLower() == searchSelection[5].ToLower() && searchString != string.Empty)
                {
                    equipmentViewModels = equipmentViewModels.Where(p => p.Term.ToString().Contains(searchString)).ToList();
                }
                else if (searchSelectionString.ToLower() == searchSelection[5].ToLower() && searchString == string.Empty)
                {
                    equipmentViewModels = equipmentViewModels.Where(p => p.Term == 0).ToList();
                }
                else if (searchSelectionString.ToLower() == searchSelection[6].ToLower() && searchString != string.Empty)
                {
                    equipmentViewModels = equipmentViewModels.Where(p => p.ProcentYear.ToString().Contains(searchString)).ToList();
                }
                else if (searchSelectionString.ToLower() == searchSelection[6].ToLower() && searchString == string.Empty)
                {
                    equipmentViewModels = equipmentViewModels.Where(p => p.ProcentYear == 0).ToList();
                }
                else if (searchSelectionString.ToLower() == searchSelection[7].ToLower() && searchString != string.Empty)
                {
                    equipmentViewModels = equipmentViewModels.Where(p => p.DeductionAmountPerMonth.ToString().Contains(searchString)).ToList();
                }
                else if (searchSelectionString.ToLower() == searchSelection[7].ToLower() && searchString == string.Empty)
                {
                    equipmentViewModels = equipmentViewModels.Where(p => Convert.ToDouble(p.DeductionAmountPerMonth) == 0).ToList();
                }
            }

            return new EquipmentIndexViewModel()
            {
                EquipmentViewModels = equipmentViewModels,
                SearchSelection = new SelectList(searchSelection),
                SearchSelectionString = searchSelectionString,
                SearchString = searchString,
                SearchStatusEquipment = searchStatusEquipment,
                StatusEquipmentSelect = new SelectList(statusEquipments),
                SearchEmployee = searchEmployee,
                EmployeeSelect = new SelectList(employees),
                SearchEquipmentType = searchEquipmentType,
                EquipmentTypeSelect = new SelectList(equipmentTypes)
            };
        }

        [HttpGet]
        public IActionResult Add(string searchSelectionString, string searchString, string searchStatusEquipment,
            string searchEmployee, string searchEquipmentType)
        {
            ViewBag.SearchSelectionString = searchSelectionString;
            ViewBag.SearchString = searchString;
            ViewBag.SearchStatusEquipment = searchStatusEquipment;
            ViewBag.SearchEmployee = searchEmployee;
            ViewBag.SearchEquipmentType = searchEquipmentType;

            // statusEquipments
            List<string> statusEquipments = _statusEquipmentService.GetAllName().ToList();
            // employees
            List<string> employees = _employeeService.GetAllIdName().ToList();
            // equipmentTypes
            List<string> equipmentTypes = _equipmentTypeService.GetAllName().ToList();

            return View(new EquipmentAddEditViewModel()
            {
                EquipmentViewModel = new EquipmentViewModel() { },
                StatusEquipmentsSelect = new SelectList(statusEquipments),
                EmployeeSelect = new SelectList(employees),

scr/Web/Controllers/EquipmentTypeController.cs
using AutoMapper;
using Core.Entities;
using Core.Exceptions;
using Core.Interfaces.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using Web.Models.EquipmentType;
using Web.Models.Position;

namespace Web.Controllers
{
    public class EquipmentTypeController : Controller
    {
        private readonly IEquipmentTypeService _equipmentTypeService;

        public EquipmentTypeController(IEquipmentTypeService equipmentTypeService)
        {
            _equipmentTypeService = equipmentTypeService;
        }

        [HttpGet]
        public IActionResult Index(string searchSelectionString, string searchString)
        {
            var equipmentTypes = _equipmentTypeService.GetAll();
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<EquipmentType, EquipmentTypeViewModel>()).CreateMapper();
            var equipmentTypesViewModels = mapper.Map<IEnumerable<EquipmentType>, List<EquipmentTypeViewModel>>(equipmentTypes);

            // list search
            List<string> searchSelection = new List<string>() { "Поиск", "Id", "Названию" };

            // search
            if (searchSelectionString != string.Empty && searchSelectionString != null && searchSelectionString != "Поиск" && searchString != null)
            {
                if (searchSelection[1].ToLower() == searchSelectionString.ToLower() && searchString != string.Empty)
                {
                    equipmentTypesViewModels = equipmentTypesViewModels.Where(p => p.Id.ToString() != null && p.Id.ToString().ToLower().Equals(searchString.ToLower())).ToList();
                }
                else if (searchSelection[1].ToLower() == searchSelectionString.ToLower() && searchString == string.Empty)
                {
                    equipmentTypesViewModels = equipmentTypesViewModels.Where(p => p.Id.ToString() == null || p.Id.ToString() == string.Empty).ToList();
                }
                else if (searchSelection[2].ToLower() == searchSelectionString.ToLower() && searchString != string.Empty)
                {
                    equipmentTypesViewModels = equipmentTypesViewModels.Where(p => p.Name != null && p.Name.ToLower().Contains(searchString.ToLower())).ToList();
                }
                else if (searchSelection[2].ToLower() == searchSelectionString.ToLower() && searchString == string.Empty)
                {
                    equipmentTypesViewModels = equipmentTypesViewModels.Where(p => p.Name == null || p.Name == string.Empty).ToList();
                }
            }

            return View(new EquipmentTypeIndexViewModel()
            {
                 EquipmentTypeViewModel = equipmentTypesViewModels,
                SearchSelection = new SelectList(searchSelection),
                SearchSelectionString = searchSelectionString,
                SearchString = searchString
            });
        }

        [HttpGet]
        public IActionResult Add(string searchSelectionString, string searchString)
        {
            ViewBag.SearchSelectionString = searchSelectionString;
            ViewBag.SearchString = searchString;

            return View();
        }

        [HttpPost]
        public IActionResult Add(PositionViewModel model, string searchSelectionString, string searchString)
        {
            ViewBag.SearchSelectionString = searchSelectionString;
            ViewBag.SearchString = searchString;

            if (ModelState.IsValid)
            {
                var equipmentType = new EquipmentType()
                {
                    Id = model.Id,
                    Name = model.Name
                };

                try
                {
                    _equipmentTypeService.Add(equipmentType);

                    return RedirectToAction("Index", new { searchSelectionString, searchString });
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError(ex.Property, ex.Message);
                }
            }

            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(int id, string searchSelectionString, string searchString)
        {
            try
            {
                _equipmentTypeService.Delete(id);
            }
            catch (ValidationException)
            {
                return RedirectToAction("Error", "Home", new { requestId = "400", errorInfo = string.Empty });
            }

            return RedirectToAction("Index", new { searchSelectionString, searchString });
        }

        [HttpGet]
        public IActionResult Edit(int id, string searchSelectionString, string searchString)
        {
            ViewBag.SearchSelectionString = searchSelectionString;
            ViewBag.SearchString = searchString;

            var equipmentType = _equipmentTypeService.Get(id);
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<EquipmentType, EquipmentTypeViewModel>()).CreateMapper();
            var equipmentTypeViewModel = mapper.Map<EquipmentType, EquipmentTypeViewModel>(equipmentType);

            return View(equipmentTypeViewModel);
        }

        [HttpPost]
        public IActionResult Edit(EquipmentTypeViewModel model, string searchSelectionString, string searchString)
        {
            ViewBag.SearchSelectionString = searchSelectionString;
            ViewBag.SearchString = searchString;

            if (ModelState.IsValid)
            {
                var mapper = new MapperConfiguration(cfg => cfg.CreateMap<EquipmentTypeViewModel, EquipmentType>()).CreateMapper();
                var equipmentType = mapper.Map<EquipmentTypeViewModel, EquipmentType>(model);

                try
                {
                    _equipmentTypeService.Edit(equipmentType);

                    return RedirectToAction("Index", new { searchSelectionString, searchString });
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError(ex.Property, ex.Message);
                }
            }

            return View(model);
        }
    }
}

scr/Web/Views/EquipmentType/Add.cshtml
@model Web.Models.EquipmentType.EquipmentTypeViewModel

@{ ViewBag.Title = "Добавление вида оборудования"; }

<div class="row mb-5">
    <div class="col-6 m-auto">
        <div class="card m-auto">
            <div class="card-header">
                <h3>Добавление вида оборудования</h3>
            </div>
            <div class="card-body">
                <form method="post" asp-controller="EquipmentType" asp-action="Add"
                      asp-route-searchSelectionString="@ViewBag.SearchSelectionString" asp-route-searchString="@ViewBag.SearchString"
                      enctype="multipart/form-data">

                    <div class="text-danger" asp-validation-summary="ModelOnly"></div>

                    <div class="form-group col-12">
                        <label asp-for="Name"></label>
                        <span class="text-danger" asp-validation-for="Name"></span><br />
                        <input class="form-control" asp-for="Name" />
                    </div>

                    <div class="form-group col-12">
                        <button type="submit" class="btn btn-primary">Добавить</button>
                        <a asp-action="Index" class="btn btn-warning"
                           asp-route-searchSelectionString="@ViewBag.SearchSelectionString"
                           asp-route-searchString="@ViewBag.SearchString">Назад</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

scr/Web/Views/EquipmentType/Edit.cshtml
@model Web.Models.EquipmentType.EquipmentTypeViewModel

@{ ViewBag.Title = "Изменение вида оборудования"; }

<div class="row mb-5">
    <div class="col-6 m-auto">
        <div class="card m-auto">
            <div class="card-header">
                <h3>Изменение вида оборудования</h3>
            </div>
            <div class="card-body">
                <form method="post" asp-controller="EquipmentType" asp-action="Edit"
                      asp-route-searchSelectionString="@ViewBag.SearchSelectionString" asp-route-searchString="@ViewBag.SearchString"
                      enctype="multipart/form-data">

                    <div class="text-danger" asp-validation-summary="ModelOnly"></div>

                    <input type="hidden" class="form-control" asp-for="Id" />

                    <div class="form-group col-12">
                        <label asp-for="Name"></label>
                        <span class="text-danger" asp-validation-for="Name"></span><br />
                        <input class="form-control" asp-for="Name" />
                    </div>

                    <div class="form-group col-12">
                        <button type="submit" class="btn btn-primary">Изменить</button>
                        <a asp-action="Index" class="btn btn-warning"
                           asp-route-searchSelectionString="@ViewBag.SearchSelectionString"
                           asp-route-searchString="@ViewBag.SearchString">Назад</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

scr/Web/Views/EquipmentType/Index.cshtml
@model Web.Models.EquipmentType.EquipmentTypeIndexViewModel

@{
    ViewBag.Title = "Виды оборудования";
}

<div class="row mb-5 mt-5">
    <div class="col-12 shadow-lg p-0 bg-white">
        <div class="card">
            <div class="card-header">
                <h3>Виды оборудования</h3>
            </div>
            <div class="card-body">
                <div class="container">

                    <form method="get">
                        <div class="form-inline form-group">
                            <label class="mr-1" asp-for="SearchSelectionString">Поиск по: </label>
                            <select class="mr-1" style="height: 1.8em;" name="searchSelectionString" asp-items="Model.SearchSelection" asp-for="SearchSelectionString"></select>
                            <label class="mr-1" asp-for="SearchString">Значение: </label>
                            <input class="mr-1" name="searchString" asp-for="SearchString" />
                            <input class="btn btn-sm btn-primary mr-1" type="submit" value="Поиск" />
                            <a class="btn btn-sm btn-danger mr-1" asp-action="Index">Обновить</a>
                            <a class="btn btn-sm btn-success mr-1" asp-action="Add" asp-route-searchSelectionString="@Model.SearchSelectionString"
                               asp-route-searchString="@Model.SearchString">Добавить вид оборудования</a>

                        </div>
                    </form>

                    @if (Model.EquipmentTypeViewModel.Any())
                    {
                        <table class="table">
                            <tr>
                                <th>
                                    Id
                                </th>
                                <th>
                                    Название
                                </th>
                                <th>

                                </th>
                            </tr>
                            @foreach (var positionViewModel in Model.EquipmentTypeViewModel)
                            {
                                <tr>
                                    <td>@positionViewModel.Id</td>
                                    <td>@positionViewModel.Name</td>
                                    <td>
                                        <form asp-action="Delete"
                                              asp-route-searchSelectionString="@Model.SearchSelectionString"
                                              asp-route-searchString="@Model.SearchString"
                                              asp-route-id="@positionViewModel.Id"
                                              method="post">

                                            <a class="btn btn-sm btn-light" asp-controller="Equipment" asp-action="Index" asp-route-searchEquipmentType="@positionViewModel.Name">К оборудованию</a>
                                            <a class="btn btn-sm btn-primary" asp-controller="EquipmentType" asp-action="Edit" asp-route-id="@positionViewModel.Id"
                                               asp-route-searchSelectionString="@Model.SearchSelectionString"
                                               asp-route-searchString="@Model.SearchString">Изменить</a>
                                            <button onclick="if (!confirm('Вы уверены, что хотите удалить этот элемент?')) { return false }" type="submit" class="btn btn-sm btn-danger">
                                                Удалить
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            }
                        </table>
                    }
                    else
                    {
                        <h2 class="text-center text-danger">
                            Список пуст
                        </h2>
                    }
                </div>
            </div>
        </div>
    </div>
</div>